export const Assets = {
  resources: {
    clay: '/images/resources/Clay.jpg',
    desert: '/images/resources/Desert.jpg',
    fabric: '/images/resources/Fabric.jpg',
    grain: '/images/resources/Grain.jpg',
    lumber: '/images/resources/Lumber.jpg',
    mineral: '/images/resources/Mineral.jpg',
  },

  board: {
    landmass: '/images/board/Landmass.jpg',
    ocean: '/images/board/ocean_animated_new.gif',
  },

  developmentCards: {
    boomingEconomy: '/images/cards/BoomingEconomy.png',
    closedMarket: '/images/cards/ClosedMarket.png',
    expertNegotiator: '/images/cards/ExpertNegotiator.png',
    extraPoint: '/images/cards/ExtraPoint.png',
    freeUpgrade: '/images/cards/FreeUpgrade.png',
    guard: '/images/cards/Guard.png',
    resourceSwap: '/images/cards/ResourceSwap.png',
    roadConstruction: '/images/cards/RoadConstruction.png',
  },

  characters: {
    astroBoy: '/images/characters/astro-boy.png',
    barbapapa: '/images/characters/barbapapa.png',
    batman: '/images/characters/batman.png',
    bert: '/images/characters/bert.png',
    bravestarr: '/images/characters/bravestarr.png',
    buggy: '/images/characters/buggy.png',
    bunny: '/images/characters/bunny.png',
    casper: '/images/characters/casper.png',
    caveman: '/images/characters/caveman.png',
    chip: '/images/characters/chip.png',
    chipmunk: '/images/characters/chipmunk.png',
    dynomutt: '/images/characters/dynomutt.png',
    flintstone: '/images/characters/flintstone.png',
    gadget: '/images/characters/gadget.png',
    garfield: '/images/characters/garfield.png',
    ghost: '/images/characters/ghost.png',
    giJoe: '/images/characters/gijoe.png',
    gobot: '/images/characters/gobot.png',
    heMan: '/images/characters/he-man.png',
    heathcliff: '/images/characters/heathcliff.png',
    jem: '/images/characters/jem.png',
    jetson: '/images/characters/jetson.png',
    josie: '/images/characters/josie.png',
    kermit: '/images/characters/kermit.png',
    lionO: '/images/characters/lion-o.png',
    mark: '/images/characters/mark.png',
    mouse: '/images/characters/mouse.png',
    optimus: '/images/characters/optimus.png',
    panther: '/images/characters/panther.png',
    puppy: '/images/characters/puppy.png',
    racer: '/images/characters/racer.png',
    rainbow: '/images/characters/rainbow.png',
    ranger: '/images/characters/ranger.png',
    scooby: '/images/characters/scooby.png',
    scrooge: '/images/characters/scrooge.png',
    sheRa: '/images/characters/she-ra.png',
    smurf: '/images/characters/smurf.png',
    snork: '/images/characters/snork.png',
    spidey: '/images/characters/spidey.png',
    teddy: '/images/characters/teddy.png',
    tenderheart: '/images/characters/tenderheart.png',
    thundarr: '/images/characters/thundarr.png',
    tmnt: '/images/characters/tmnt.png',
    tom: '/images/characters/tom.png',
    trakker: '/images/characters/trakker.png',
    voltron: '/images/characters/voltron.png',
    woody: '/images/characters/woody.png',
    wuzzle: '/images/characters/wuzzle.png',
    yogi: '/images/characters/yogi.png',
    zummi: '/images/characters/zummi.png',
  },
} as const;
