export const Assets = {
  resources: {
    clay: '/images/resources/Clay%20new.jpg',
    desert: '/images/resources/Desert%20new.jpg',
    fabric: '/images/resources/Fabric%20new.jpg',
    grain: '/images/resources/Grain%20new.jpg',
    lumber: '/images/resources/Lumber%20new.jpg',
    mineral: '/images/resources/Mineral%20new.jpg',
  },

  board: {
    landmass: '/images/board/Landmass.jpg',
    ocean: '/images/board/Ocean%20animated%20new.gif',
  },

  developmentCards: {
    boomingEconomy: '/images/cards/BoomingEconomy.png',
    closedMarket: '/images/cards/ClosedMarket.png',
    expertNegotiator: '/images/cards/ExpertNegotiator.png',
    extraPoint: '/images/cards/ExtraPoint.png',
    freeUpgrade: '/images/cards/FreeUpgrade.png',
    guard: '/images/cards/Guard.png',
    resourceSwap: '/images/cards/ResourceSwap.png',
    roadConstruction: '/images/cards/RoadConstruction.png',
  },

  characters: {
    astroBoy: '/images/characters/Astro-Boy.png',
    barbapapa: '/images/characters/Barbapapa.png',
    batman: '/images/characters/Batman.png',
    bert: '/images/characters/Bert.png',
    bravestarr: '/images/characters/Bravestarr.png',
    buggy: '/images/characters/Buggy.png',
    bunny: '/images/characters/Bunny.png',
    casper: '/images/characters/Casper.png',
    caveman: '/images/characters/Caveman.png',
    chip: '/images/characters/Chip.png',
    chipmunk: '/images/characters/Chipmunk.png',
    dynomutt: '/images/characters/Dynomutt.png',
    flintstone: '/images/characters/Flintstone.png',
    gadget: '/images/characters/Gadget.png',
    garfield: '/images/characters/Garfield.png',
    ghost: '/images/characters/Ghost.png',
    giJoe: '/images/characters/GIJoe.png',
    gobot: '/images/characters/Gobot.png',
    heMan: '/images/characters/He-Man.png',
    heathcliff: '/images/characters/Heathcliff.png',
    jem: '/images/characters/Jem.jpg',
    jetson: '/images/characters/Jetson.png',
    josie: '/images/characters/Josie.png',
    kermit: '/images/characters/Kermit.png',
    lionO: '/images/characters/Lion-O.png',
    mark: '/images/characters/Mark.png',
    mouse: '/images/characters/Mouse.png',
    optimus: '/images/characters/Optimus.png',
    panther: '/images/characters/Panther.png',
    puppy: '/images/characters/Puppy.png',
    racer: '/images/characters/Racer.png',
    rainbow: '/images/characters/Rainbow.png',
    ranger: '/images/characters/Ranger.png',
    scooby: '/images/characters/Scooby.png',
    scrooge: '/images/characters/Scrooge.png',
    sheRa: '/images/characters/She-Ra.png',
    smurf: '/images/characters/Smurf.png',
    snork: '/images/characters/Snork.png',
    spidey: '/images/characters/Spidey.png',
    teddy: '/images/characters/Teddy.png',
    tenderheart: '/images/characters/Tenderheart.png',
    thundarr: '/images/characters/Thundarr.png',
    tmnt: '/images/characters/TMNT.png',
    tom: '/images/characters/Tom.png',
    trakker: '/images/characters/Trakker.png',
    voltron: '/images/characters/Voltron.png',
    woody: '/images/characters/Woody.png',
    wuzzle: '/images/characters/Wuzzle.png',
    yogi: '/images/characters/Yogi.png',
    zummi: '/images/characters/Zummi.png',
  },
} as const;
